services:
  viajes-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: viajesdb
    ports:
      - "3307:3306"
    volumes:
      - viajes-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  gestionusuarios-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      viajes-mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://viajes-mysql:3306/viajesdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: toor

volumes:
  viajes-mysql-data:



